// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bibsmobile.model;

import com.bibsmobile.model.AwardCategory;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AwardCategory_Roo_Configurable {
    
    declare @type: AwardCategory: @Configurable;
    
}
