/**
 * 
 */
package com.bibsmobile.model;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Copy of a badge. All badges are queried on their trigger type and whether they
 * are enabled when a trigger comes in from a queue. If the badge matches, the a
 * UserBadge is created.
 * @author galen
 *
 */
public class Badge {
	/**
	 * Autogenerated id
	 */
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
	
	private BadgeTriggerEnum trigger;

	private boolean active = false;
	
	private String name;
	
	private String url;
	
	private Date timeStart;
	
	private Date timeEnd;
	
	@OneToMany(fetch = FetchType.LAZY, cascade = { CascadeType.ALL }, mappedBy = "badge")
	Set <UserBadge> granted;
}
