// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bibsmobile.model;

import com.bibsmobile.model.EventRegistration;
import javax.persistence.Entity;

privileged aspect EventRegistration_Roo_Jpa_Entity {
    
    declare @type: EventRegistration: @Entity;
    
}
