// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bibsmobile.model;

import com.bibsmobile.model.UserAuthority;

privileged aspect UserAuthority_Roo_JavaBean {
    
    public void UserAuthority.setAuthority(String authority) {
        this.authority = authority;
    }
    
}
